// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file distance_sensorSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/subscriber/Subscriber.h>
#include <fastrtps/attributes/SubscriberAttributes.h>

#include <fastrtps/Domain.h>

#include "distance_sensorSubscriber.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

distance_sensorSubscriber::distance_sensorSubscriber() : mp_participant(nullptr), mp_subscriber(nullptr) {}

distance_sensorSubscriber::~distance_sensorSubscriber() {	Domain::removeParticipant(mp_participant);}

bool distance_sensorSubscriber::init(const ros::NodeHandle& private_nh)
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_subscriber"); //You can put the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Subscriber

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = NO_KEY;
    Rparam.topic.topicDataType = myType.getName(); //Must be registered before the creation of the subscriber
    Rparam.topic.topicName = "distance_sensorPubSubTopic";
    mp_subscriber = Domain::createSubscriber(mp_participant,Rparam, static_cast<SubscriberListener*>(&m_listener));
    if(mp_subscriber == nullptr)
    {
        return false;
    }

    m_listener.nh_ = private_nh;
    m_listener.distance_sensor_publisher_ = m_listener.nh_.advertise<px4_msgs::DistanceSensor>("/px4_micrortps_ros/distance_sensor/out", 10);

    return true;
}

void distance_sensorSubscriber::SubListener::onSubscriptionMatched(Subscriber* sub,MatchingInfo& info)
{
    (void)sub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "Subscriber distance_sensor matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "Subscriber distance_sensor unmatched" << std::endl;
    }
}

void distance_sensorSubscriber::SubListener::onNewDataMessage(Subscriber* sub)
{
    // Take data
    distance_sensor st;

    if(sub->takeNextData(&st, &m_info))
    {
        if(m_info.sampleKind == ALIVE)
        {
            px4_msgs::DistanceSensorPtr distance_sensor_msg(new px4_msgs::DistanceSensor);
            convertUORBToPX4Message(st, distance_sensor_msg); 

            distance_sensor_publisher_.publish(distance_sensor_msg);
        }
    }
}

void distance_sensorSubscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the Subscriber. "<<std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}


void distance_sensorSubscriber::SubListener::convertUORBToPX4Message(const distance_sensor& st, px4_msgs::DistanceSensorPtr& px4_msg_ptr)
{
    px4_msg_ptr->timestamp = st.timestamp_();

    px4_msg_ptr->min_distance = st.min_distance_();

    px4_msg_ptr->max_distance = st.max_distance_();

    px4_msg_ptr->current_distance = st.current_distance_();

    px4_msg_ptr->variance = st.variance_();

    px4_msg_ptr->signal_quality = st.signal_quality_();
    
    px4_msg_ptr->type = st.type_();

    px4_msg_ptr->h_fov = st.h_fov_();
    px4_msg_ptr->v_fov = st.v_fov_();

    px4_msg_ptr->q[0] = st.q()[0];
    px4_msg_ptr->q[1] = st.q()[1];
    px4_msg_ptr->q[2] = st.q()[2];
    px4_msg_ptr->q[3] = st.q()[3];

    px4_msg_ptr->orientation = st.orientation_();
    
}