// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file vehicle_local_position_setpointPublisher.cpp
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/publisher/Publisher.h>
#include <fastrtps/attributes/PublisherAttributes.h>

#include <fastrtps/Domain.h>

#include <thread>
#include <chrono>

#include "vehicle_local_position_setpointPublisher.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

vehicle_local_position_setpointPublisher::vehicle_local_position_setpointPublisher() : mp_participant(nullptr), mp_publisher(nullptr) {}

vehicle_local_position_setpointPublisher::~vehicle_local_position_setpointPublisher() {	Domain::removeParticipant(mp_participant);}

bool vehicle_local_position_setpointPublisher::init()
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_publisher");  //You can put here the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Publisher

    PublisherAttributes Wparam;
    Wparam.topic.topicKind = NO_KEY;
    Wparam.topic.topicDataType = myType.getName();  //This type MUST be registered
    Wparam.topic.topicName = "vehicle_local_position_setpointPubSubTopic";

    mp_publisher = Domain::createPublisher(mp_participant,Wparam,static_cast<PublisherListener*>(&m_listener));

    if(mp_publisher == nullptr)
    {
        return false;
    }

    std::cout << "Publisher created, waiting for Subscribers." << std::endl;
    return true;
}

void vehicle_local_position_setpointPublisher::PubListener::onPublicationMatched(Publisher* pub,MatchingInfo& info)
{
    (void)pub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "Publisher matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "Publisher unmatched" << std::endl;
    }
}

void vehicle_local_position_setpointPublisher::run(const px4_msgs::VehicleLocalPositionSetpoint& input)
{
    vehicle_local_position_setpoint st;

    st.timestamp_(input.timestamp);        
    
    st.x_(input.x);
    st.y_(input.y);
    st.z_(input.z);

    st.vx_(input.vx);
    st.vy_(input.vy);
    st.vz_(input.vz);

    std::array<float, 3> acceleration = {  input.acceleration[0] , input.acceleration[1] , input.acceleration[2] };
    st.acceleration(acceleration);

    std::array<float, 3> thrust = { input.thrust[0] , input.thrust[1] , input.thrust[2] };
    st.thrust(thrust);

    st.yaw_(input.yaw);
    st.yawspeed_(input.yawspeed);

    mp_publisher->write(&st);
}
