// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file timesyncSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/subscriber/Subscriber.h>
#include <fastrtps/attributes/SubscriberAttributes.h>

#include <fastrtps/Domain.h>

#include "timesyncSubscriber.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

timesyncSubscriber::timesyncSubscriber() : mp_participant(nullptr), mp_subscriber(nullptr) {}

timesyncSubscriber::~timesyncSubscriber() {	Domain::removeParticipant(mp_participant);}

bool timesyncSubscriber::init(const ros::NodeHandle& private_nh)
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_subscriber"); //You can put the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Subscriber

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = NO_KEY;
    Rparam.topic.topicDataType = myType.getName(); //Must be registered before the creation of the subscriber
    Rparam.topic.topicName = "timesyncPubSubTopic";
    mp_subscriber = Domain::createSubscriber(mp_participant,Rparam, static_cast<SubscriberListener*>(&m_listener));
    if(mp_subscriber == nullptr)
    {
        return false;
    }

    m_listener.nh_ = private_nh;
    m_listener.timesync_publisher_ = m_listener.nh_.advertise<px4_msgs::Timesync>("/px4_micrortps_ros/timesync/out", 10);

    return true;
}

void timesyncSubscriber::SubListener::onSubscriptionMatched(Subscriber* sub,MatchingInfo& info)
{
    (void)sub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "Subscriber timesync  matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "Subscriber timesync unmatched" << std::endl;
    }
}

void timesyncSubscriber::SubListener::onNewDataMessage(Subscriber* sub)
{
    // Take data
    timesync st;

    if(sub->takeNextData(&st, &m_info))
    {
        if(m_info.sampleKind == ALIVE)
        {
            px4_msgs::TimesyncPtr msg_ptr(new px4_msgs::Timesync);
            msg_ptr->timestamp = st.timestamp_();
            msg_ptr->seq = st.seq_();
            msg_ptr->tc1 = st.tc1_();
            msg_ptr->ts1 = st.ts1_();

            // ROS_INFO("Received: %llu, %llu, %llu, %llu", msg_ptr->timestamp, msg_ptr->seq, msg_ptr->tc1, msg_ptr->ts1);
            // std::cout <<  "Timesync Nodelet:   "<< msg_ptr << std::endl;
            timesync_publisher_.publish(msg_ptr);
        }
    }
}

void timesyncSubscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the Subscriber. "<<std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}

