// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file input_rcSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/subscriber/Subscriber.h>
#include <fastrtps/attributes/SubscriberAttributes.h>

#include <fastrtps/Domain.h>

#include "input_rcSubscriber.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

input_rcSubscriber::input_rcSubscriber() : mp_participant(nullptr), mp_subscriber(nullptr) {}

input_rcSubscriber::~input_rcSubscriber() {	Domain::removeParticipant(mp_participant);}

bool input_rcSubscriber::init(const ros::NodeHandle& private_nh)
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_subscriber"); //You can put the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Subscriber

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = NO_KEY;
    Rparam.topic.topicDataType = myType.getName(); //Must be registered before the creation of the subscriber
    Rparam.topic.topicName = "input_rcPubSubTopic";
    mp_subscriber = Domain::createSubscriber(mp_participant,Rparam, static_cast<SubscriberListener*>(&m_listener));
    if(mp_subscriber == nullptr)
    {
        return false;
    }

    m_listener.nh_ = private_nh;
    m_listener.input_rc_publisher_ = m_listener.nh_.advertise<px4_msgs::InputRc>("/px4_micrortps_ros/input_rc/out", 10);

    return true;
}

void input_rcSubscriber::SubListener::onSubscriptionMatched(Subscriber* sub,MatchingInfo& info)
{
    (void)sub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "Subscriber input_rc matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "Subscriber input_rc unmatched" << std::endl;
    }
}

void input_rcSubscriber::SubListener::onNewDataMessage(Subscriber* sub)
{
    // Take data
    input_rc st;

    if(sub->takeNextData(&st, &m_info))
    {
        if(m_info.sampleKind == ALIVE)
        {
            ROS_INFO("[input_rcSubscriber] Received ALIVE data");

            px4_msgs::InputRcPtr msg_ptr(new px4_msgs::InputRc);
            convertUORBToPX4Message(st, msg_ptr); 

            input_rc_publisher_.publish(msg_ptr);
        }
    }
}

void input_rcSubscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the Subscriber. "<<std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}

void input_rcSubscriber::SubListener::convertUORBToPX4Message(const input_rc& uorb_msg, px4_msgs::InputRcPtr& px4_msg)
{
    px4_msg->timestamp = uorb_msg.timestamp_();
    px4_msg->timestamp_last_signal = uorb_msg.timestamp_last_signal_();
    px4_msg->channel_count = uorb_msg.channel_count_();
    px4_msg->rssi = uorb_msg.rssi_();
    px4_msg->rc_failsafe = uorb_msg.rc_failsafe_();
    px4_msg->rc_lost = uorb_msg.rc_lost_();
    px4_msg->rc_lost_frame_count = uorb_msg.rc_lost_frame_count_();
    px4_msg->rc_total_frame_count = uorb_msg.rc_total_frame_count_();
    px4_msg->rc_ppm_frame_length = uorb_msg.rc_ppm_frame_length_();
    px4_msg->input_source = uorb_msg.input_source_();

    for (int i = 0; i < uorb_msg.values().size(); i++)
    {
        px4_msg->values[i] = uorb_msg.values()[i];
    }


}