// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sensor_combinedSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/subscriber/Subscriber.h>
#include <fastrtps/attributes/SubscriberAttributes.h>

#include <fastrtps/Domain.h>

#include "sensor_combinedSubscriber.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

sensor_combinedSubscriber::sensor_combinedSubscriber() : mp_participant(nullptr), mp_subscriber(nullptr) {}

sensor_combinedSubscriber::~sensor_combinedSubscriber() {	Domain::removeParticipant(mp_participant);}

bool sensor_combinedSubscriber::init(const ros::NodeHandle& private_nh)
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_subscriber"); //You can put the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Subscriber

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = NO_KEY;
    Rparam.topic.topicDataType = myType.getName(); //Must be registered before the creation of the subscriber
    Rparam.topic.topicName = "sensor_combinedPubSubTopic";
    mp_subscriber = Domain::createSubscriber(mp_participant,Rparam, static_cast<SubscriberListener*>(&m_listener));
    if(mp_subscriber == nullptr)
    {
        return false;
    }

    m_listener.nh_ = private_nh;
    m_listener.sensor_combined_publisher_ = m_listener.nh_.advertise<px4_msgs::SensorCombined>("/px4_micrortps_ros/sensor_combined/out", 10);

    return true;
}

void sensor_combinedSubscriber::SubListener::onSubscriptionMatched(Subscriber* sub,MatchingInfo& info)
{
    (void)sub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "Subscriber sensor_combined matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "Subscriber sensor_combined unmatched" << std::endl;
    }
}

void sensor_combinedSubscriber::SubListener::onNewDataMessage(Subscriber* sub)
{
    // Take data
    sensor_combined st;

    if(sub->takeNextData(&st, &m_info))
    {
        if(m_info.sampleKind == ALIVE)
        {
            px4_msgs::SensorCombinedPtr msg_ptr(new px4_msgs::SensorCombined);
            convertUORBToPX4Message(st, msg_ptr); 
            // ROS_INFO("uorb_msg.gyro_rad(): %f, %f, %f", msg_ptr->gyro_rad[0], msg_ptr->gyro_rad[1], msg_ptr->gyro_rad[2]);
            sensor_combined_publisher_.publish(msg_ptr);
        }
    }
}

void sensor_combinedSubscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the Subscriber. "<<std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}

void sensor_combinedSubscriber::SubListener::convertUORBToPX4Message(const sensor_combined& uorb_msg, px4_msgs::SensorCombinedPtr& px4_msg)
{
    px4_msg->timestamp = uorb_msg.timestamp_();

    px4_msg->gyro_rad[0] = uorb_msg.gyro_rad()[0];
    px4_msg->gyro_rad[1] = uorb_msg.gyro_rad()[1];
    px4_msg->gyro_rad[2] = uorb_msg.gyro_rad()[2];

 

    px4_msg->gyro_integral_dt = uorb_msg.gyro_integral_dt_();
    px4_msg->accelerometer_timestamp_relative = uorb_msg.accelerometer_timestamp_relative_();

    px4_msg->accelerometer_m_s2[0] = uorb_msg.accelerometer_m_s2()[0];
    px4_msg->accelerometer_m_s2[1] = uorb_msg.accelerometer_m_s2()[1];
    px4_msg->accelerometer_m_s2[2] = uorb_msg.accelerometer_m_s2()[2];

    px4_msg->accelerometer_integral_dt = uorb_msg.accelerometer_integral_dt_();

    px4_msg->accelerometer_clipping = uorb_msg.accelerometer_clipping_();

    //does not exist in v.1.12.3    
    //px4_msg->accel_calibration_count = uorb_msg.accel_calibration_count_();
    //px4_msg->gyro_calibration_count = uorb_msg.gyro_calibration_count_();

}