// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file vehicle_land_detectedSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/subscriber/Subscriber.h>
#include <fastrtps/attributes/SubscriberAttributes.h>

#include <fastrtps/Domain.h>

#include "vehicle_land_detectedSubscriber.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

vehicle_land_detectedSubscriber::vehicle_land_detectedSubscriber() : mp_participant(nullptr), mp_subscriber(nullptr) {}

vehicle_land_detectedSubscriber::~vehicle_land_detectedSubscriber() {	Domain::removeParticipant(mp_participant);}

bool vehicle_land_detectedSubscriber::init(const ros::NodeHandle& private_nh)
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_subscriber"); //You can put the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Subscriber

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = NO_KEY;
    Rparam.topic.topicDataType = myType.getName(); //Must be registered before the creation of the subscriber
    Rparam.topic.topicName = "vehicle_land_detectedPubSubTopic";
    mp_subscriber = Domain::createSubscriber(mp_participant,Rparam, static_cast<SubscriberListener*>(&m_listener));
    if(mp_subscriber == nullptr)
    {
        return false;
    }

    m_listener.nh_ = private_nh;
    m_listener.vehicle_land_detected_publisher_ = m_listener.nh_.advertise<px4_msgs::VehicleLandDetected>("/px4_micrortps_ros/vehicle_land_detected/out", 10);

    return true;
}

void vehicle_land_detectedSubscriber::SubListener::onSubscriptionMatched(Subscriber* sub,MatchingInfo& info)
{
    (void)sub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "Subscriber matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "Subscriber unmatched" << std::endl;
    }
}

void vehicle_land_detectedSubscriber::SubListener::onNewDataMessage(Subscriber* sub)
{
    // Take data
    vehicle_land_detected st;

    if(sub->takeNextData(&st, &m_info))
    {
        if(m_info.sampleKind == ALIVE)
        {
            px4_msgs::VehicleLandDetectedPtr msg_ptr(new px4_msgs::VehicleLandDetected);
            convertUORBToPX4Message(st, msg_ptr); 

            vehicle_land_detected_publisher_.publish(msg_ptr);
        }
    }
}


void vehicle_land_detectedSubscriber::SubListener::convertUORBToPX4Message(const vehicle_land_detected &st, px4_msgs::VehicleLandDetectedPtr & px4_msg_ptr)
{
    px4_msg_ptr->timestamp = st.timestamp_();

    px4_msg_ptr->freefall = st.freefall_();
    px4_msg_ptr->ground_contact = st.ground_contact_();
    px4_msg_ptr->maybe_landed = st.maybe_landed_();
    px4_msg_ptr->landed = st.landed_();

    px4_msg_ptr->in_ground_effect = st.in_ground_effect_();
    px4_msg_ptr->in_descend = st.in_descend_();    

    px4_msg_ptr->has_low_throttle = st.has_low_throttle_();  

    px4_msg_ptr->vertical_movement = st.vertical_movement_();  
    px4_msg_ptr->horizontal_movement = st.horizontal_movement_(); 

    px4_msg_ptr->close_to_ground_or_skipped_check = st.close_to_ground_or_skipped_check_();  

    //TODO does not exist in v1.12.3
    //px4_msg_ptr->at_rest = st.at_rest_();  
}

void vehicle_land_detectedSubscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the Subscriber. "<<std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}

