// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file debug_key_valuePublisher.cpp
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#include <fastrtps/participant/Participant.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/publisher/Publisher.h>
#include <fastrtps/attributes/PublisherAttributes.h>

#include <fastrtps/Domain.h>

#include <thread>
#include <chrono>

#include "debug_key_valuePublisher.h"

using namespace eprosima::fastrtps;
using namespace eprosima::fastrtps::rtps;

debug_key_valuePublisher::debug_key_valuePublisher() : mp_participant(nullptr), mp_publisher(nullptr) {}

debug_key_valuePublisher::~debug_key_valuePublisher() {	Domain::removeParticipant(mp_participant);}

bool debug_key_valuePublisher::init()
{
    // Create RTPSParticipant

    ParticipantAttributes PParam;
    PParam.rtps.setName("Participant_publisher");  //You can put here the name you want
    mp_participant = Domain::createParticipant(PParam);
    if(mp_participant == nullptr)
    {
        return false;
    }

    //Register the type

    Domain::registerType(mp_participant, static_cast<TopicDataType*>(&myType));

    // Create Publisher

    PublisherAttributes Wparam;
    Wparam.topic.topicKind = NO_KEY;
    Wparam.topic.topicDataType = myType.getName();  //This type MUST be registered
    Wparam.topic.topicName = "debug_key_valuePubSubTopic";

    mp_publisher = Domain::createPublisher(mp_participant,Wparam,static_cast<PublisherListener*>(&m_listener));

    if(mp_publisher == nullptr)
    {
        return false;
    }

    std::cout << "Publisher created, waiting for Subscribers." << std::endl;
    return true;
}

void debug_key_valuePublisher::PubListener::onPublicationMatched(Publisher* pub,MatchingInfo& info)
{
    (void)pub;

    if (info.status == MATCHED_MATCHING)
    {
        n_matched++;
        std::cout << "debug key value Publisher matched" << std::endl;
    }
    else
    {
        n_matched--;
        std::cout << "debug key value Publisher unmatched" << std::endl;
    }
}

void debug_key_valuePublisher::run(const px4_msgs::DebugKeyValue& input)
{
    debug_key_value st;

    st.timestamp_(input.timestamp);

    std::array<char, 10> key = { input.key[0], input.key[1], input.key[2], input.key[3], input.key[4], input.key[5], input.key[6], input.key[7], input.key[8], input.key[9] }; 
    st.key(key);

    st.value_(input.value);

    mp_publisher->write(&st);
}
