// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file mavlink_log.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MAVLINK_LOG_H_
#define _MAVLINK_LOG_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(mavlink_log_SOURCE)
#define mavlink_log_DllAPI __declspec( dllexport )
#else
#define mavlink_log_DllAPI __declspec( dllimport )
#endif // mavlink_log_SOURCE
#else
#define mavlink_log_DllAPI
#endif
#else
#define mavlink_log_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


const uint8_t mavlink_log__ORB_QUEUE_LENGTH = 8;
typedef std::array<char, 127> mavlink_log__char_array_127;
/*!
 * @brief This class represents the structure mavlink_log defined by the user in the IDL file.
 * @ingroup MAVLINK_LOG
 */
class mavlink_log
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport mavlink_log();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~mavlink_log();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object mavlink_log that will be copied.
     */
    eProsima_user_DllExport mavlink_log(const mavlink_log &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object mavlink_log that will be copied.
     */
    eProsima_user_DllExport mavlink_log(mavlink_log &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object mavlink_log that will be copied.
     */
    eProsima_user_DllExport mavlink_log& operator=(const mavlink_log &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object mavlink_log that will be copied.
     */
    eProsima_user_DllExport mavlink_log& operator=(mavlink_log &&x);

    /*!
     * @brief This function sets a value in member timestamp_
     * @param _timestamp_ New value for member timestamp_
     */
    eProsima_user_DllExport void timestamp_(uint64_t _timestamp_);

    /*!
     * @brief This function returns the value of member timestamp_
     * @return Value of member timestamp_
     */
    eProsima_user_DllExport uint64_t timestamp_() const;

    /*!
     * @brief This function returns a reference to member timestamp_
     * @return Reference to member timestamp_
     */
    eProsima_user_DllExport uint64_t& timestamp_();

    /*!
     * @brief This function copies the value in member text
     * @param _text New value to be copied in member text
     */
    eProsima_user_DllExport void text(const mavlink_log__char_array_127 &_text);

    /*!
     * @brief This function moves the value in member text
     * @param _text New value to be moved in member text
     */
    eProsima_user_DllExport void text(mavlink_log__char_array_127 &&_text);

    /*!
     * @brief This function returns a constant reference to member text
     * @return Constant reference to member text
     */
    eProsima_user_DllExport const mavlink_log__char_array_127& text() const;

    /*!
     * @brief This function returns a reference to member text
     * @return Reference to member text
     */
    eProsima_user_DllExport mavlink_log__char_array_127& text();
    /*!
     * @brief This function sets a value in member severity_
     * @param _severity_ New value for member severity_
     */
    eProsima_user_DllExport void severity_(uint8_t _severity_);

    /*!
     * @brief This function returns the value of member severity_
     * @return Value of member severity_
     */
    eProsima_user_DllExport uint8_t severity_() const;

    /*!
     * @brief This function returns a reference to member severity_
     * @return Reference to member severity_
     */
    eProsima_user_DllExport uint8_t& severity_();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const mavlink_log& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint64_t m_timestamp_;
    mavlink_log__char_array_127 m_text;
    uint8_t m_severity_;
};

#endif // _MAVLINK_LOG_H_